labels:
  - pairs:
      app: bot-notifier
    includeSelectors: true

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: bot-notifier
    newName: freberg/discorddeputy-bot-notifier
    newTag: 0.7.1
