server.port: 8082
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      group:
        readiness:
          include: db
      show-details: always
      probes:
        enabled: true
  server.port: 7082
spring:
  application:
    name: discorddeputy-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/discordnotifications}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  threads:
    virtual:
      enabled: true
