---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: discord-deputy
  namespace: discord-deputy
spec:
  encryptedData:
    discord_token: AgAWJikBqj2766HhcCKgUaxCUDRNwqBFUXdHvluTJnGlhhDAMg+kFSTxuhjnwQkKAc4caiy5de52xGr7R5rifQjJHr+HoOFJqKk4O3Of4RT/zyjYeiViQ3jU42p1yEbga9ouB1/2HEI5dlsldV4L5SE05DM/uDq93UTyyR3NV8fZv52Gqs8mfOfyv0xTo0NM+qMD4G6fRJ7l5rQQoiixr9/6KOeFJJOm7jTDwABT8DhtLQ4OOCMKPEvRSgVvRJ8Uruzzv3yDulPCHONa7DwilTwPt6Alejg869kpWnbTufvqULJ5b3mCoxsW0ky7hyJPCf4j1MdrC9kbSV+Kc+V6oHwu5SdLbIOFbpQ6PNs/OcyIGVg4QmhVzgkmc8PgFUcu9+PkAfkFY/2pl086Wyp3dF2ELfK6G9zUCTfInC6gu9+/E7gvnouea5tX3SWT3xHIuI3riHTHVSHF4rvsUX85+DASp43aevejkYOTVrKg480rCogs3DEMDNmT2mlnjOirYeqQGzCV0XCo8wfBPqS5VPNe3UwJDp6N10L0GgHQMV++jbDOXQTlkUiCxu9aTK6UIIg12jGEZQm4h2/Pu51NPtqLAxE3u6ZMD0OJ0NRoF8klchoWKJSPCXOc513ucBfOqGSeCBlJGW2jdC4yzan6esY+bSxz4GHlPOx5lSEXVu90tSVNute3t20rSmUj7Lek+Zp+dAPy+doQWx53L0nkfZfFUYeve1pFqZ4jXtNhpm0UxEHnoJipL2PJIS7HBRmaqcjiiCGfppPP6ijQ/m7ypK56ukMPcUQ7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: discord-deputy
      namespace: discord-deputy
