labels:
  - pairs:
      app: fetcher-epic
    includeSelectors: true

resources:
  - rollout.yaml
  - analysis-template.yaml

images:
  - name: fetcher-epic
    newName: freberg/discorddeputy-fetcher-epic
    newTag: 0.7.4
  - name: integration-test
    newName: freberg/discorddeputy-integration-test
    newTag: 0.7.4
