- op: add
  path: /spec/template/spec/containers/0/startupProbe
  value:
    httpGet:
      path: /actuator/health/liveness
      port: monitor
    failureThreshold: 30
    periodSeconds: 10


- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    httpGet:
      path: /actuator/health/liveness
      port: monitor
    periodSeconds: 30
    failureThreshold: 5

- op: add
  path: /spec/template/spec/containers/0/readinessProbe
  value:
    httpGet:
      path: /actuator/health/readiness
      port: monitor
    periodSeconds: 30
    failureThreshold: 5
