- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      memory: 300Mi
      cpu: '1'
    limits:
      memory: 300Mi
      cpu: '2'
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: JDK_JAVA_OPTIONS
    value: "-XX:MaxRAMPercentage=40.0"
