labels:
  - pairs:
      app: fetcher-steam
    includeSelectors: true

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: fetcher-steam
    newName: freberg/discorddeputy-fetcher-steam
    newTag: 0.7.8
