server.port: 8081
management:
  endpoints:
    web.exposure.include: "*"
  endpoint.health:
    group.readiness.include: rabbit
    probes.enabled: true
    show-details: always
  server.port: 7081
  endpoint.shutdown.access: unrestricted
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:rabbitmq}
    password: ${RABBIT_PASSWORD:rabbitmq}
  cloud.stream:
    bindings:
      offerSource-out-0:
        destination: ${OUTPUT_EXCHANGE:source-notifications}

epicGames.pollFrequency:
  duration: 30
  timeUnit: MINUTES