server.port: 8085

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      group:
        readiness:
          include: r2dbc,rabbit
      show-details: always
      probes:
        enabled: true
      validate-group-membership: false # validation does not find r2dbc
  server.port: 7085
spring:
  application.name: discorddeputy-processor
  sql.init.mode: always
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/discordnotifications}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:rabbitmq}
    password: ${RABBIT_PASSWORD:rabbitmq}
  cloud.stream:
    bindings:
      processor-in-0:
        destination: ${INPUT_EXCHANGE:source-notifications}
        group: processor-group
      processor-out-0:
        destination: ${OUTPUT_EXCHANGE:bot-notifications}