labels:
  - pairs:
      app: api
    includeSelectors: true

resources:
  - rollout.yaml
  - analysis-template.yaml
  - service.yaml

images:
  - name: api
    newName: freberg/discorddeputy-api
    newTag: 0.7.11
