apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    canary:
      stableService: api
      canaryService: api-canary
      maxUnavailable: 0
      maxSurge: 1
      steps:
      - setWeight: 50
      - analysis:
          templates:
            - templateName: api-smoke-test-template
          args:
            - name: service-name
              value: api-canary.discord-deputy.svc.cluster.local:8082
      - setWeight: 100
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: api
          imagePullPolicy: Always
          name: api
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://discord-deputy-db-ro:5432/app
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: discord-deputy-db-app
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-deputy-db-app
                  key: password
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
          ports:
            - containerPort: 8082
              name: main
              protocol: TCP
            - containerPort: 7082
              name: monitor
              protocol: TCP
